### ISSUE TITLE
Configurator footprint over time

### ISSUE THREAD

**Issue by AndreBiedenkapp** [automl/CAVE#101]
Configurator footprints (formerly known as configuration visualization) plotting over time.
This could be achieved in two ways.

- As a gif (impossible with mousover effects)
- As an interactive plot where the time to plot is given as input

**Comment by mlindauer** [comment]
Have you ever tried to run it on a considerable amount of data points? I'm running the dev branch on 20k data points and it computes this plot now for more than 30 minutes. My guess would be that most users won't wait for 30minutes :-(

**Comment by AndreBiedenkapp** [comment]
No I haven't tried with that many data points

**Comment by shukon** [comment]
@mlindauer sorry, but I don't think there is a quicker way to get overtime-plots at the moment... Configurator footprints still are just very slow in general. I will try to do a proper analysis to see if we can optimize somewhere.

**Comment by shukon** [comment]
Closed since speed of cfp is different topic, opened #155 for suggested improvement
