### ISSUE TITLE
Configurator footprint plotting origin

### ISSUE THREAD

**Issue by AndreBiedenkapp** [automl/CAVE#103]
If the origin of configurations is known (such as in SMAC), it would be useful to be able to differentiate if configurations were selected by random search or any other origin.

**Comment by shukon** [comment]
Afaik, the origin is not saved in SMAC in any way at the moment.
I see three intuitive ways to make the origin available:
1. Add it as an optional entry in the runhistory, e.g.:
`[[config_id, "instance_name", seed], [cost, runtime,  {"__enum__": "StatusType.SUCCESS"}, {"additional_info": "some info"}, origin]]`
2. Write it/append it to the additional_info, which I have rarely seen in use so far, e.g.:
`{"additional_info": "some info"}` -> `{"additional_info": "some info_RANDOM/LOCALSEARCH"}`
3. Keep an extra file mapping `RunKey`s (as in the `RunHistory`) to origin... feels like memory waste though.

Do you have other ideas?

**Comment by AndreBiedenkapp** [comment]
The origin is not stored in the runhistory but with the configuration itself.
With the latest ConfigSpace, a configuration has the attribute origin (see https://github.com/automl/ConfigSpace/blob/159602ebd816f8dbe3637e298766e84de41be9ac/ConfigSpace/configuration_space.py#L866-L869)

When the acquisition function class was made more general, it was also made use of the origin attribute of configurations. For example in LocalSearch._maximize https://github.com/automl/SMAC3/blob/56a5af9e3666ae54f7c126b62ae44852af65842d/smac/optimizer/ei_optimization.py#L208
or in RandomSearch._maximize https://github.com/automl/SMAC3/blob/56a5af9e3666ae54f7c126b62ae44852af65842d/smac/optimizer/ei_optimization.py#L339-L346
So the information is there but currently not used.

**Comment by shukon** [comment]
if available, footprint origin is listed in hover-tooltip with #123
