### ISSUE TITLE
Have not found instance file

### ISSUE THREAD

**Issue by mlindauer** [automl/CAVE#109]
```
python ../../../../../scripts/cave.py --folders output/ --ta_exec output/
INFO:cave.cavefacade:Saving results to CAVE_output
ERROR:smac.scenario.scenario.Scenario:Have not found instance file: output/training.txt
```

**Comment by shukon** [comment]
Could you check whether #112 resolves this issue for your folder-structure?
Please note that `--ta_exec` should be the folder, from which the relative paths of the scenario-files can be reached (the original execution-dir of SMAC), in your case I think you can leave it at the default (`.`).
Also, `--folders` expects a list of the actual subfolder-names - so in your case, can you please run:
`python ../../../../../scripts/cave.py --folders output/*`

**Comment by shukon** [comment]
@mlindauer please check if current development branch solves the issue using
 `python ../../../../../scripts/cave.py --folders output/*`

**Comment by mlindauer** [comment]
Yes, thank you.
