### ISSUE TITLE
Plots not rendered in jupyter notebooks (Error: (...) Models must be owned by only a single document (...))

### ISSUE THREAD

**Issue by shukon** [automl/CAVE#209]
With error messages similar to `RuntimeError: Models must be owned by only a single document,
Scatter(id='4659', ...) is already in a doc`.
This is very bad and happens due to the environment of the notebooks and bokeh's behaviour on it. More information [here](https://github.com/bokeh/bokeh/issues/7323) and [here](https://stackoverflow.com/a/51564139).

Solution: when calling `get_jupyter` on any analyzer-object, no `bokeh.embed.components` must be called!

**Comment by shukon** [comment]
The error should be fixed in development branch now. However there should be more work moved into the baseclass, to ease changes like this.

**Comment by PhMueller** [comment]
As a short workaround, it also works for me to downgrade bokeh to version 1.13.0
 
`pip install bokeh==0.13.0`
