### ISSUE TITLE
LPI uncertainty

### ISSUE THREAD

**Issue by shukon** [automl/CAVE#221]
Is still incredibly high... relevant code is [here in pimp](https://github.com/automl/ParameterImportance/blob/b2eaf5769e2c1c3526fa5c61b380f6ed2e507927/pimp/evaluator/local_parameter_importance.py#L269-L275). @AndreBiedenkapp do you have any idea why this happens?

![bug2](https://user-images.githubusercontent.com/9417378/52017137-bfc5cc80-24e6-11e9-8b37-cc31f44a5be4.png)

**Comment by AndreBiedenkapp** [comment]
Oh wow that is incredibly high.

Just from looking at the pyimp code I'm not sure anymore that you got the right uncertainty.
I believe that the "variance_dict" tracks the model uncertainty, whereas the parameter uncertainty/variance is tracked in "overall_var[param]" (see [here](https://github.com/automl/ParameterImportance/blob/b2eaf5769e2c1c3526fa5c61b380f6ed2e507927/pimp/evaluator/local_parameter_importance.py#L238-L239)), which is also used to compute the importance values.

**Comment by shukon** [comment]
So this is a little confusing now. Current state: we use the unnormalized model uncertainty (for each parameter: mean over the variances of all random forests used to predict neighbor performances) to estimate LPI-uncertainty. However, as we have seen for the NEMO-data, this can lead to very high uncertainty.
Since we normalize the importance over the parameters anyway, I figured we could as well normalize the uncertainties (dividing every uncertainty by the sum of all uncertainties). Since this is getting more and more abstract, I suppose:
1) we normalize somehow over the uncertainties.
2) we change the way it's presented, because currently it looks the same way as fANOVA while the meaning is inherently different. LPI in it's current form has nothing to do with the _mean +/- std_ -form it's currently being displayed in.

**Comment by mlindauer** [comment]
Hi,

I'm a bit confused.
Here is what I would do:

1. Compute the (normalized) LPI importance of a parameter by using a single (randomized) tree. 
(Please note that the variance used in LPI is not the model uncertainty but the performance variance across different parameter values. Thus you can compute LPI on a single tree.)
2. Repeat 1. several times such that you have several importance values for each parameters
3. Compute mean and stdev across these

Actually, I also thought that you did the same for the fANOVA uncertainty. 

If it is still unclear, maybe we should meet in person again soon.

**Comment by shukon** [comment]
So I do think it's clear now and it seems to be working. I was going about it completely different. Do you think it is crucial to use only one tree? Simply repeating the prediction with a randomized forest as usual seems to work fine. Will merge today and send you the updated report.

**Comment by mlindauer** [comment]
> Do you think it is crucial to use only one tree? Simply repeating the prediction with a randomized forest as usual seems to work fine.

What do you mean? For a given input, the predictions of a fitted RF should be fixed and not randomized. 

If you refer to fitting several RFs:
I would actually expect that if your forests are large enough (e.g., thousands of trees), all your forests should have the same predictions (for a given input). So the variance across predictions (for a given input) decreases if the number of trees in a forest increases. Hence, I would go for a single tree.

**Comment by shukon** [comment]
I refered to fitting several RFs. Ok, I'll figure out how to use a single tree.

**Comment by mlindauer** [comment]
You simply fit the RF (as always) and than you don't get the predictions of the entire RF, but of each individual tree.
