### ISSUE TITLE
fANOVA pairwise plots missing in report

### ISSUE THREAD

**Issue by ashraaghav** [automl/CAVE#224]
(Might be related to issue #58)

I was running CAVE with BOHB on the example provided with CAVE. The report generated had only 1 pairwise marginal plot (more specifically, the lowest among the 4). However, the plots were generated and stored in the contents folder. Is that a bug?

**Comment by shukon** [comment]
Hi, thank you for filing the issue.
This is indeed a bug, and it should be fixed in the development-branch. Can you check by installing CAVE from the dev-branch (`pip install git+https://github.com/automl/CAVE.git@development`)?

**Comment by ashraaghav** [comment]
Yes, it is working fine now.
