### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by ArlindKadra** [automl/CAVE#227]
Hey,
In the Readme, the link to the BOHB example notebook is non-existent.

**Comment by shukon** [comment]
Thanks for pointing that out, the corresponding repository seems to be not publicly available at the moment. We will figure out a solution asap.

**Comment by mlindauer** [comment]
Hi,

@shukon The repo will be private until we submitted the paper. (new policy in our group, more details in person)

@ArlindKadra If you want to have access to the repo, please ask me and I will grant you the access.
