### ISSUE TITLE
No module named 'smac.utils.util_funcs'

### ISSUE THREAD

**Issue by WrightKD** [automl/CAVE#249]
I am working with the following code : [Example SVM](https://github.com/automl/SMAC3/blob/master/examples/SMAC4HPO_svm.py).It runs perfectly.I now want to use CAVE on the results from the HPO.But I get the following error:

`from smac.utils.util_funcs import get_types
ModuleNotFoundError: No module named 'smac.utils.util_funcs'`

I think it has something to do with this [issue](https://github.com/automl/SMAC3/issues/527)

**Comment by shukon** [comment]
Thanks a lot for the report. Upon investigation, there are a few things, that changed with SMAC version 0.11.0, full support will not be implemented before the weekend. However everything for BOHB-analysis should work fine with dev-branches of CAVE and ParameterImportance, except for configurator-footprints (disable with `--no_configurator_footprint`)

**Comment by shukon** [comment]
This issue should by now be fully resolved, by updating to CAVE 1.1.8
