### ISSUE TITLE
How to analyse a SMAC3 run with CAVE

### ISSUE THREAD

**Issue by PetarMPetrov** [automl/CAVE#251]
Hi, I am not sure this is the place to ask this question as it is not really an issue, but I could not find any other contact details. Please let me know if there is a better forum.

I would like to use SMAC and analyse its results with CAVE. The smac optimisation I performed is very similar to the [SVM example](https://github.com/automl/SMAC3/blob/master/examples/SMAC4HPO_svm.py) but done in a jupyter notebook. 

Here is a very simple [repository](https://github.com/PetarMPetrov/smac_run_output)
I run SMAC from a notebook and then try to run CAVE from another notebook. (the notebooks are also in .py and .html format for easy inspection). Also, all the outputs from SMAC are in the repository. 

The CAVE notebook has an error in the last output field. 
I think it has to do with the fact that it is looking for a target algorithm implementation, but I am not sure why. My understanding is that once the optimisation process outputs all its history, then CAVE can be used to analyse it without needing to know what the ta is. Looks like I am wrong though. 

What do I have to change to make this simple example work?

**Update**
After trying some more stuff, I identified that the same error occurs when I define a constant hyperparameter with integer value, run smac, which saves the configuration space in a file, and I try to recreate the runhistory (the snippet is the second part, so it assumes the run is already performed and saved):
```python
from smac.scenario.scenario import Scenario
import os
run_dir = 'smac_output_cs4_runcount_80_ntrain_1024/run_1'
with open(os.path.join(run_dir,'scenario.txt')) as fin:
    scenario_kwargs = {} 
    for line in fin.readlines():
        key, val = line.split('=')
        scenario_kwargs[key.strip()] = val.strip()
old_scenario = Scenario(scenario_kwargs)

from smac.runhistory.runhistory import RunHistory
rh1 = RunHistory(aggregate_func=None)
rh1.load_json(
    os.path.join(run_dir,'runhistory.json'),
    old_scenario.cs,
)
```

**Error Message**
```text
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-a2804aeeaf0e> in <module>
      3 rh1.load_json(
      4     os.path.join(run_dir,'runhistory.json'),
----> 5     old_scenario.cs,
      6 )

~/anaconda3/envs/sandbox_env/lib/python3.6/site-packages/smac/runhistory/runhistory.py in load_json(self, fn, cs)
    402             int(id_): Configuration(
    403                 cs, values=values, origin=config_origins.get(id_, None)
--> 404             ) for id_, values in all_data["configs"].items()
    405         }
    406 

~/anaconda3/envs/sandbox_env/lib/python3.6/site-packages/smac/runhistory/runhistory.py in <dictcomp>(.0)
    402             int(id_): Configuration(
    403                 cs, values=values, origin=config_origins.get(id_, None)
--> 404             ) for id_, values in all_data["configs"].items()
    405         }
    406 

ConfigSpace/configuration_space.pyx in ConfigSpace.configuration_space.Configuration.__init__()

ValueError: Trying to set illegal value '42' (type '<class 'int'>') for hyperparameter 'random_state, Type: Categorical, Choices: {42}, Default: 42' (default-value has type '<class 'str'>').
```

**Comment by shukon** [comment]
The problem is the configspace - there are problems recovering integers or booleans in `CategoricalHyperparameter`s as they are imported as strings. While this is annoying and we need better errors, it's complicated and probably not really worth fixing (at least not in CAVE), since using  `.json` instead of `.pcs` format works just fine. So [for your example](https://github.com/PetarMPetrov/smac_run_output/pull/1) I created a `configspace.json` in your SMAC-run and redirected the `scenario.txt`-`paramfile` to that json. Now it works perfect.
Are you using the newest SMAC-version? Because then I'll file this as an issue there, since SMAC should at least save both configspace-formats...
Feel free to ask, if there is anything unclear :)

**Comment by PetarMPetrov** [comment]
Thanks Joshua! The example is running indeed. It should get me started with CAVE. I am using SMAC 0.11 now and I do get `configspace.json` as an output, but when I created the repo, I think I may have used 0.10.
