### ISSUE TITLE
Segmentation Fault (core dumped)

### ISSUE THREAD

**Issue by Mahsaft** [automl/CAVE#292]
Hi

I have to use CAVE for my student project. After I had installed cave, I tried to use the quickstart but I reached the following error. I would be glad, if you could help me.

I tried CAVE 1.3 and CAVE 1.4 but both of them followed the same error.

![image](https://user-images.githubusercontent.com/48664418/98010262-c4738f00-1df6-11eb-80a1-24e84d0c6476.png)

I did the following recipe:
1. download CAVE-1.3.0 from github
2. venv in pycharm (intrepreter)
3. exchange '>=' in reqiurements.txt with '=='
4.	cat requirements.txt | xargs -n 1 -L 1 pip install
	pip install .
5.     cave examples/smac3/example_output/* --ta_exec_dir examples/smac3/ --output output/smac3_example

I am using: Ubuntu 20.04.1 LTS, Intel® Core™ i7-8550U CPU @ 1.80GHz , Python 3.8.5 and Pycharm.
I use the following packages and versions for CAVE 1.3.0

ConfigSpace | 0.4.9 
Cython | 0.29.21 
Jinja2 | 2.11.2 
MarkupSafe | 1.1.1 
Pillow | 8.0.1 
PyImp | 1.1.0 
PyYAML | 5.3.1 
Pyro4 | 4.80 
argcomplete | 1.12.1 
bokeh | 1.1.0 
cave | 1.3.0 
certifi | 2020.6.20 
cycler | 0.10.0 
docutils | 0.16 
fanova | 2.0.11
hpbandster | 0.7.4 
joblib | 0.17.0 
kiwisolver | 1.3.1 
lazy-import | 0.2.2 
matplotlib | 3.3.2 
netifaces | 0.10.9
nose | 1.3.7 
numpy | 1.19.4 
packaging | 20.4 
pandas | 1.1.4 
patsy | 0.5.1 
pip | 20.2.4 
psutil | 5.7.3 
pynisher | 0.6.1 
pyparsing | 2.4.7
pyrfr | 0.8.0 
python-dateutil | 2.8.1
pytz | 2020.4
scikit-learn | 0.21.3 
scipy | 1.5.3 
selenium | 3.141.0
serpent | 1.30.2 
setuptools | 50.3.2 
six | 1.15.0 
sklearn | 0.0 
smac | 0.12.0 
sobol-seq | 0.2.0 
statsmodels | 0.12.1
tornado | 6.1 
tqdm | 4.51.0 
typing | 3.7.4.3 
typing-extensions | 3.7.4.3 
urllib3 | 1.25.11

**Comment by shukon** [comment]
Hi, can you please run using the DEBUG flag and post the full output? (just append `--verbose DEBUG`)

**Comment by shukon** [comment]
Actually, can you also post the your swig-version? (`$ swig -version`)

There is a known issue with pyrfr, see [here in fanova issues](https://github.com/automl/fanova/issues/102). This looks a lot like it, but we'll know more with the debug-log.
The tldr is: uninstall swig 4, install swig 3. However getting rid of swig 4 is not that easy, needs a few reinstalls of packages, here's what helped someone with the swig-problem:

```
pip uninstall smac
pip uninstall pyrfr
pip install pyrfr --no-cache-dir
pip install smac[all] --no-cache-dir
```

no idea how to that in pycharm, but if you find that this is the solution to your problem, please report back and leave the issue open :)

**Comment by AndreBiedenkapp** [comment]
@Mahsaft I also think that the issue might likely be related to swig.

**Comment by Mahsaft** [comment]
@shukon @AndreBiedenkapp thanks a lot. I follow the instruction and switch to swig 3. now It works on my core but somehow it still have same error on my pycharm virtual environment.

**Comment by shukon** [comment]
Mhm - I don't know enough about pycharm, but sometimes uninstalling old versions can be a pain. Glad to hear it works at all, good luck with your pycharm and let's hope this will be solved at some point upstream.

**Comment by AndreBiedenkapp** [comment]
In pycharm you can change the interpreter for individual projects (see https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html).
So you could change it for the project where you use CAVE.
Since the issue was solved with SWIG3 I'll mark it as closed.
