### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by AndreBiedenkapp** [automl/CAVE#46]
When running SpySMAC on a SMAC run that had a budget of 10 hours, I get a Memory Error:

> DEBUG:smac.scenario.scenario.Scenario:Scenario Options:
> DEBUG:smac.scenario.scenario.Scenario:output_dir = 
> DEBUG:smac.scenario.scenario.Scenario:always_race_default = False
> DEBUG:smac.scenario.scenario.Scenario:overall_obj = par10
> DEBUG:smac.scenario.scenario.Scenario:deterministic = False
> DEBUG:smac.scenario.scenario.Scenario:cost_for_crash = 2147483647.0
> DEBUG:smac.scenario.scenario.Scenario:maxR = 2000
> DEBUG:smac.scenario.scenario.Scenario:ta_run_limit = inf
> DEBUG:smac.scenario.scenario.Scenario:run_obj = runtime
> DEBUG:smac.scenario.scenario.Scenario:initial_incumbent = DEFAULT
> DEBUG:smac.scenario.scenario.Scenario:execdir = .
> DEBUG:smac.scenario.scenario.Scenario:minR = 1
> DEBUG:smac.scenario.scenario.Scenario:test_inst_fn = smac3-output_2017-10-12_15:57:19_(400766)_run18372/test.txt
> DEBUG:smac.scenario.scenario.Scenario:shared_model = False
> DEBUG:smac.scenario.scenario.Scenario:pcs_fn = smac3-output_2017-10-12_15:57:19_(400766)_run18372/params_small.pcs
> DEBUG:smac.scenario.scenario.Scenario:intensification_percentage = 0.5
> DEBUG:smac.scenario.scenario.Scenario:wallclock_limit = 36000.0
> DEBUG:smac.scenario.scenario.Scenario:cutoff = 5.0
> DEBUG:smac.scenario.scenario.Scenario:algo_runs_timelimit = inf
> DEBUG:smac.scenario.scenario.Scenario:feature_fn = smac3-output_2017-10-12_15:57:19_(400766)_run18372/features.txt
> DEBUG:smac.scenario.scenario.Scenario:abort_on_first_run_crash = True
> DEBUG:smac.scenario.scenario.Scenario:train_inst_fn = smac3-output_2017-10-12_15:57:19_(400766)_run18372/training.txt
> INFO:smac.utils.io.traj_logging.TrajLogger:No output directory for trajectory logging specified -- trajectory will not be logged.
> DEBUG:spysmac.spyfacade:Update global rh with all available rhs!
> DEBUG:spysmac.spyfacade:Combined number of Runhistory data points: 1. # Configurations: 58242. # Runhistories: 29001
> INFO:spysmac.spyfacade:Completing data using epm.
> DEBUG:smac.runhistory.runhistory2epm.RunHistory2EPM4Cost:Transform runhistory into X,y format
> DEBUG:smac.runhistory.runhistory2epm.RunHistory2EPM4Cost:Converted 57302 observations
> DEBUG:smac.utils.validate.Validator:Training model with data of shape X: (57302, 93), y:(57302, 1)
> DEBUG:smac.utils.validate.Validator:Gathered 2 configurations for mode def+inc.
> INFO:smac.utils.validate.Validator:Collected 750 runs from 2 configurations on 500 instances with 1 repetitions. Reusing 250 runs from given runhistory.
> DEBUG:smac.utils.validate.Validator:Predicting desired 750 runs, data has shape (750, 93) and NaNs are present: False (if so, will be zeroed)
> INFO:smac.utils.validate.Validator:Saving validation-results in validation_rh.json
> DEBUG:spysmac.plotter:Plot CDF to test/cdf.png
> DEBUG:spysmac.plotter:Plot scatter to test/scatter.png
> INFO:SampleViz:Number of Configurations: 29001
> Traceback (most recent call last):
>   File "SpySMAC/scripts/spy.py", line 17, in <module>
>     spysmac.main_cli()
>   File "/home/biedenka/git/SpySMAC/spysmac/spysmac_cli.py", line 75, in main_cli
>     fanova="fanova" in param_imp)
>   File "/home/biedenka/git/SpySMAC/spysmac/spyfacade.py", line 210, in analyze
>     confviz = self.plotter.visualize_configs(self.scenario, self.global_rh)
>   File "/home/biedenka/git/SpySMAC/spysmac/plot/plotter.py", line 191, in visualize_configs
>     return sz.run()
>   File "/home/biedenka/git/SpySMAC/spysmac/plot/confs_viz/viz_sampled_confs.py", line 95, in run
>     red_dists = self.get_mds(dists)
>   File "/home/biedenka/git/SpySMAC/spysmac/plot/confs_viz/viz_sampled_confs.py", line 271, in get_mds
>     return mds.fit_transform(dists)
>   File "/home/biedenka/miniconda3/envs/spysmactest/lib/python3.4/site-packages/sklearn/manifold/mds.py", line 425, in fit_transform
>     return_n_iter=True)
>   File "/home/biedenka/miniconda3/envs/spysmactest/lib/python3.4/site-packages/sklearn/manifold/mds.py", line 254, in smacof
>     eps=eps, random_state=random_state)
>   File "/home/biedenka/miniconda3/envs/spysmactest/lib/python3.4/site-packages/sklearn/manifold/mds.py", line 111, in _smacof_single
>     stress = ((dis.ravel() - disparities.ravel()) ** 2).sum() / 2
> MemoryError

As you can see, there was quite a lot of data collected during the 10 hour scenario.

There are two suggestions on my part:
1. Limit the amount of configurations that are considered for the plot. (Maybe you can throw away very uninteresting configurations in boring parts of the space?)
2. You might be able to lower the required RAM substantially if you only store the upper trianglular matrix here:
https://github.com/automl/SpySMAC/blob/682151477ede7a23f1e274dae2aa0e0b807ea13a/spysmac/plot/confs_viz/viz_sampled_confs.py#L216-L223

(PS: The loop might be a good idea to put in some logging output #44  that a user knows what is happening in the background)

**Comment by AndreBiedenkapp** [comment]
@shukon I think this is no longer an issue. Am I correct?

**Comment by shukon** [comment]
I think so too
