### ISSUE TITLE
Unify performance-term over project

### ISSUE THREAD

**Issue by shukon** [automl/CAVE#60]
Currently "performance", "cost" and "loss" are used all in the same context in different parts of the module

**Comment by AndreBiedenkapp** [comment]
@shukon I think this can be closed

**Comment by shukon** [comment]
@AndreBiedenkapp well, I never got around to do it, so it's still not really consistent, what term would we use?

**Comment by AndreBiedenkapp** [comment]
Okay my bad. I would tend to use performance.
What do you think?

**Comment by shukon** [comment]
Sounds good. There has been some [discussion in SMAC](https://github.com/automl/SMAC3/issues/266) about this, but that was more about the scenario-objective I think. I will fix this.
