### ISSUE TITLE
Visualizing configspace

### ISSUE THREAD

**Issue by shukon** [automl/CAVE#63]
- only plot one run at a time
- distinguish between random configs and model predicted configs (how?)

**Comment by mlindauer** [comment]
> distinguish between random configs and model predicted configs (how?)

right now, we don't save the origin of a configuration in the runhistory files. Therefore, the information is not available. We would need to first fix SMAC.

**Comment by AndreBiedenkapp** [comment]
@shukon I think this issue is not relevant anymore as we've got the configurator footprint

**Comment by shukon** [comment]
Agreed.
