### ISSUE TITLE
Algorithm Footprints plots not consistent

### ISSUE THREAD

**Issue by mlindauer** [automl/CAVE#64]
Looking at the new algorithm footprints plots, I wondered why the principal components change in each plot? The number of instances and the PCA should be the same in all plots, right?

PS: Please remove the title in all plots.

**Comment by shukon** [comment]
Actually, the footprints are currently structured as follows:
conf_all: all labeled instances for conf
conf_n: labeled instances for conf for cluster n

so PCA is the same for all plots, we are looking at different parts of the plot.

**Comment by mlindauer** [comment]
ah, ok. could we please still use the same ranges on the axes?

**Comment by shukon** [comment]
We do, we just "zoom in" on the individual clusters. I could remove the plots for the individual clusters. Or maybe I'm misinterpreting what you mean?

**Comment by mlindauer** [comment]
No, please don't zoom in.

Maybe we could also remove the plots for the individual clusters. Do you think that these are important?

**Comment by shukon** [comment]
I think they are more interesting than the overview-plots, because you can actually see the individual instances and (sometimes...) make out small areas with worse performance. I will remove for now, but keep in code in case I can convince you in the next meeting or with some better data. :)

**Comment by AndreBiedenkapp** [comment]
@shukon Can this be closed?

**Comment by shukon** [comment]
Yep.
