### ISSUE TITLE
Algorithm Footprint Plots with mouse-over effect

### ISSUE THREAD

**Issue by mlindauer** [automl/CAVE#72]
It would be great if we could add a mouse-over in the algorithm footprint plots such that we will know the name of each instance. [low priority]

However, I worry that we will have to restructure the html layout again in the near future. Loading the report from disk is already slow (in particular because of the interactive configuration sampling plot). If we add even more interactive plots, it will kill the report soon.

**Comment by shukon** [comment]
#154
