### ISSUE TITLE
Correlation Plots/Feature analysis - test instances?

### ISSUE THREAD

**Issue by shukon** [automl/CAVE#92]
Hi, currently neither SMAC nor CAVE consider features for test-instances, right? At least they are not added to the `feature_array` [in SMAC.](https://github.com/automl/SMAC3/blob/56a5af9e3666ae54f7c126b62ae44852af65842d/smac/scenario/scenario.py#L404-L405). They are, however, added to the `feature_dict`, [if present in the feature-file.](https://github.com/automl/SMAC3/blob/56a5af9e3666ae54f7c126b62ae44852af65842d/smac/scenario/scenario.py#L396-L400) That makes [considering them in feature analysis, i.e. in correlation plots](https://github.com/automl/CAVE/blob/2217d076873e97ff9d843718565e644933cd7546/cave/feature_analysis/feature_analysis.py#L52) unnecessary or even harmful(?). @mlindauer, @AndreBiedenkapp should we remove test-instances from feature analysis?

**Comment by AndreBiedenkapp** [comment]
Yes, the test instances are unnecessary and can be removed. They should however not factor in the computed OOB anyways.
