### ISSUE TITLE
3D footprint plots

### ISSUE THREAD

**Issue by AndreBiedenkapp** [automl/CAVE#97]
Currently in the 2D reduced space, the instances in the footprint plots tend to overalp alot. This makes it difficult to see a correlation between the scatter and the footprint plots.
Adding a third dimension (as interactive 3d plot for the html report) could alleviate this problem and give more insights into the cluster of instances.

**Comment by shukon** [comment]
mpld3 does not support 3d-plots. I tried a few things including [bokeh](https://demo.bokehplots.com/apps/surface3d), which needs node.js (and also has limited documentation on embedding the plots in html without use of bokeh-servers) and [plotly](https://plot.ly/python/3d-scatter-plots/), which I also could not embed in an html-structure.
However, I added [non-interactive 3d-plots](https://github.com/automl/CAVE/blob/8b91803ba8bc89d3c09c4961ea3e778d8d187866/cave/plot/algorithm_footprint.py#L262) for now:
![incumbent2d](https://user-images.githubusercontent.com/9417378/34918788-04dc4886-f959-11e7-8ddc-dd9d24cbe3fc.png)
![incumbent3d](https://user-images.githubusercontent.com/9417378/34918789-04fd7ff6-f959-11e7-88b4-1b1821ae5320.png)

**Comment by AndreBiedenkapp** [comment]
Looks great!
So now we can get some Idea how much overlap there is.
From the coloring I assume that it again determines the percent of green by the number of instances on the exact same point or did you change that for 3D?

**Comment by shukon** [comment]
Oh, I did not merge that branch yet. Will do and post plots asap.

**Comment by AndreBiedenkapp** [comment]
If adding interactive plots is a hassle, we could simply add 3D plots from different viewpoints.

**Comment by shukon** [comment]
Introduced in #125
